Repository deepeth/mars, pull requests merged in 2022-08, with the labels that each got.

#61 chore: fix parquet import
  ethetl/src/exporters/receipts.rs
  ethetl/src/exporters/token_transfers.rs
  schemas/databend/logs.sql
  schemas/databend/receipts.sql
Labels: pr-chore

#60 ci: link openssl static
  .github/workflows/dev.yml
  .github/workflows/release.yml
  Cross.toml
  docker/cross/Dockerfile.aarch64-unknown-linux-gnu
  docker/cross/Dockerfile.x86_64-unknown-linux-gnu
Labels: pr-build

#63 feat: reduce the default batch size
  common/configs/src/eth.rs
Labels: pr-feature

#66 ci: release docker image to ghcr.io
  .github/workflows/release.yml
  .gitignore
  docker/Dockerfile
Labels: pr-build

#71 feat: add abi decode
  Cargo.lock
  common/eth/Cargo.toml
  common/eth/src/abi.rs
  common/eth/src/decode.rs
  common/eth/src/encode.rs
  common/eth/src/lib.rs
  common/eth/tests/it/decode.rs
  common/eth/tests/it/encode.rs
  common/eth/tests/it/main.rs
  ethetl/Cargo.toml
  ethetl/src/exporters/logs.rs
  ethetl/src/exporters/token_transfers.rs
  ethetl/src/exporters/transactions.rs
Labels: pr-feature

#77 feat: remove write s3 directly
  common/configs/src/lib.rs
  common/configs/src/storage.rs
  common/storages/src/lib.rs
  common/storages/src/storage.rs
  ethetl/src/contexts/context.rs
Labels: pr-feature

#78 chore: change parquet as default format
  common/configs/src/eth.rs
Labels: pr-chore

#79 chore: add snowflake
  ethetl/tests/it/exporters/blocks.rs
  ethetl/tests/it/exporters/receipts.rs
  schemas/databend/1_schema.sql
  schemas/databend/2_example.sql
  schemas/databend/README.md
  schemas/databend/blocks.sql
  schemas/databend/ens.sql
  schemas/databend/logs.sql
  schemas/databend/receipts.sql
  schemas/databend/token_transfers.sql
  schemas/databend/transactions.sql
  schemas/snowflake/1_schema.sql
  schemas/snowflake/2_example.sql
  schemas/snowflake/README.md
Labels: pr-chore
